### ISSUE TITLE
Safari 11.03/macOS 10.13.3 (17D102) DNS failures when one of these lists is in AdBlock

### ISSUE THREAD

**Issue by paulbeard** [notracking/hosts-blocklists#59] opened 2018-02-27 00:29 UTC
In the past week or so I have seen DNS requests for services to Google properties (*.google.com, youtube.com) fail in Safari but not in Chrome. I use TomatoUSB and have installed https://github.com/notracking/hosts-blocklists as one of many adblock lists. They are not reachable by ping, either, even though Chrome will load them. I have tested all the adblock files and this is the one that triggers it. I'll check later to see if I can find the specific commit. It doesn't make any sense to me, either, that Chrome can connect whan commandline ping fails. If I force a DNS query with dig, ping will work and Safari can then make the connection. But how a browser operates above that seems odd to me. 

I haven't explored rolling back through the commits to find it yet but here's how I ended up here.

**Comment by notracking** [comment] 2018-02-27 13:58
Hi Paul,

Did you try [clearing the cache of Chome](https://superuser.com/questions/203674/how-to-clear-flush-the-dns-cache-in-google-chrome)? That might solve you issue with the difference in behaviour from Safari. Furthermore I need more details about the websites that you are trying to open / use when encountering issues. I did not find any issues with my daily use of youtube / google.

A usefull way of debugging is to enable dnsmasq query-log and copy the last couple of lines as soon as you encounter some issues.

**Comment by cbuijs** [comment] 2018-02-27 17:10
@paulbeard 

My guess...

Chrome falls back to their own DNS servers (8.8.8.8 etc) if one of their domains cannot be resolved locally and sometimes even use hardcoded addresses for their services (particulary for search).

As ping is not working as well, their must be something wrong with your DNS setup as chrome falls back because of it. Use "dig" or "nslookup" to see if you can resolve "www.google.com", do NOT use ping as it is a ICMP test tool, not to test DNS (not trying to sound like a dad here) :-).

**Comment by Mausy5043** [comment] 2018-02-27 18:28
If `ping` fails. Try `ping6`.

**Comment by notracking** [comment] 2018-03-10 13:26
I was not certain that chrome actually falls back to hardcoded dns entries: 8.8.8.8 and 8.8.4.4. On my local network I've forwarded those ips to my local dns using iptables, because the Chromecast uses those dns servers no matter what the dhcp host tells it to use (very nasty behavior). I can only recommend using Firefox, but that is just my 2c ;)

Since I cannot see any issue that might be caused by our lists, I'm closing this ticket. In case I'm wrong please update and I will re-open.

**Closed by notracking** 2018-03-10 13:26 UTC

**Comment by paulbeard** [comment] 2018-03-10 16:59
> On Mar 10, 2018, at 5:26 AM, notracking <notifications@github.com> wrote:
> 
> Since I cannot see any issue that might be caused by our lists, I'm closing this ticket. In case I'm wrong please update and I will re-open.
> 
> 

That’s fine. I’ll see if I can find any more granular detail. It could be some kind of buffer overrun in the router software or something, given the number of lists I have loaded. I wasn’t very careful about how I added them, to my shame. I’ll  try backing them out to see what differences I see.

**Comment by paulbeard** [comment] 2019-05-04 19:43
I have been seeing this over the past week but I have issues I am working on as well: not sure if this is me or you. 


dig svn.freebsd.org

; <<>> DiG 9.8.7 <<>> svn.freebsd.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 45786
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;svn.freebsd.org.		IN	A

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat May 04 12:39:48 PDT 2019
;; MSG SIZE  rcvd: 33

I can ping google, et al, and freebsd.org but this svn site seems to be hit or miss.

**Comment by notracking** [comment] 2019-05-05 07:15
```
dig svn.freebsd.org

; <<>> DiG 9.10.3-P4-Debian <<>> svn.freebsd.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61801
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;svn.freebsd.org.		IN	A

;; ANSWER SECTION:
svn.freebsd.org.	2179	IN	CNAME	svnmir.geo.freebsd.org.
svnmir.geo.freebsd.org.	150	IN	A	213.138.116.72

;; Query time: 89 msec
;; SERVER: 10.9.0.1#53(10.9.0.1)
;; WHEN: Sun May 05 09:14:54 CEST 2019
;; MSG SIZE  rcvd: 85
```
